# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Django', 'Django'), ('MEAN', 'MEAN'), ('iOS', 'iOS'), ('Server', 'Server')], default='Django', max_length=15),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
